// Generated by CoffeeScript 1.9.3
(function() {
  var app, express;

  express = require("express");

  app = express();

  app.route("/hello").get(function(req, res) {
    debugger;
    console.log("http request", process.pid.id);
    res.send('world');
  });

  app.listen(3000, function() {
    console.log("listening", process.pid);
  });

}).call(this);
