// Generated by CoffeeScript 1.9.3
(function() {
  var cluster, express_cluster;

  express_cluster = require('express-cluster');

  cluster = require('cluster');

  if (cluster.isMaster) {
    console.log("master!");
  } else if (cluster.isWorker) {
    console.log("child!");
  } else {
    console.log("alien!");
  }

  express_cluster(function(w) {
    require('./app');
  }, {
    verbose: true
  });

}).call(this);
